In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3122, 6191, 3106, 517],
 [3122, 6191, 3106, 3179],
 [3122, 240, 3106, 4797],
 [9041, 9724, 9137, 4842, 8421],
 [9041, 9724, 9137, 4842, 4218],
 [9187, 3122, 5291, 3106, 7811],
 [3177, 4900, 8057, 4842]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3122 6191 3106  517]
 [   0    0    0    0 3122 6191 3106 3179]
 [   0    0    0    0 3122  240 3106 4797]
 [   0    0    0 9041 9724 9137 4842 8421]
 [   0    0    0 9041 9724 9137 4842 4218]
 [   0    0    0 9187 3122 5291 3106 7811]
 [   0    0    0    0 3177 4900 8057 4842]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\HP\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 883ms/step


array([[[ 0.01152699,  0.02077338,  0.04819944,  0.01879506,
          0.00340379, -0.02251996,  0.02009536, -0.03762051,
         -0.0042259 ,  0.02347841],
        [ 0.01152699,  0.02077338,  0.04819944,  0.01879506,
          0.00340379, -0.02251996,  0.02009536, -0.03762051,
         -0.0042259 ,  0.02347841],
        [ 0.01152699,  0.02077338,  0.04819944,  0.01879506,
          0.00340379, -0.02251996,  0.02009536, -0.03762051,
         -0.0042259 ,  0.02347841],
        [ 0.01152699,  0.02077338,  0.04819944,  0.01879506,
          0.00340379, -0.02251996,  0.02009536, -0.03762051,
         -0.0042259 ,  0.02347841],
        [ 0.04893431,  0.03425889,  0.0343206 ,  0.03517356,
         -0.02568245, -0.01303667, -0.02553378, -0.03063585,
          0.02225873,  0.01912469],
        [ 0.03015453, -0.02414091,  0.00845499, -0.01275256,
         -0.04992436,  0.02774853,  0.01953138, -0.04441122,
         -0.00423173,  0.01606121],
        [-0.04615629, -0.03734379,  0.0201281 , -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3122, 6191, 3106,  517])

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None